class AddFieldsToUsers < ActiveRecord::Migration[5.0]
  def change
    add_column :users, :first_name, :string
    add_column :users, :last_name, :string

    add_column :users, :is_admin, :boolean, default: false
    add_column :users, :autogenerated_password, :boolean, default: false

    add_column :users, :use_billing, :boolean, default: false, null: false
  end
end
