class User < ApplicationRecord
  include ActiveModel::Validations

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  has_one :billing_address, as: :addressable, dependent: :destroy
  has_one :shipping_address, as: :addressable, dependent: :destroy

  def self.from_omniauth(auth)
    user = find_by(provider: auth.provider, uid: auth.uid)
    return user if user

    user = find_by(email: auth.info.email)
    if user
      user.update(provider: auth.provider, uid: auth.uid)
    else
      create do |u|
        u.email = auth.info.email
        u.password = Devise.friendly_token[0, 20]
      end
    end
  end

#   def self.from_omniauth(auth)
#     find_or_create_by(email: auth.info.email) do |user|
#       user.provider = auth.provider
#       user.uid = auth.uid
#       user.password = Devise.friendly_token[0, 20]
#       # user.autogenerated_password = true
#     end
#   end
end
